<?php

/**
 * Default catalog for Kriya.Lokal pitch storefront.
 * Seller overrides merge client-side (localStorage).
 */
return [
    [
        'id' => 'garuda-cyberpunk-tee',
        'name' => 'Garuda x Cyberpunk Tee',
        'price' => 350000,
        'category' => 'T-Shirt',
        'heritage' => 'Barong Garuda',
        'description' => 'Motif Garuda direinterpretasi dalam gaya neon cyberpunk untuk generasi digital.',
        'story' => 'Cerita visual mengenai kekuatan dan perlindungan—nilai yang sama dari Sang Garuda—dalam bahasa desain futuristik yang relevan dengan streetwear kontemporer.',
        'image' => 'garuda-cyberpunk.jpg',
        'featured' => true,
        'stock' => 42,
    ],
    [
        'id' => 'wayang-comic-tee',
        'name' => 'Wayang x Comic Style Tee',
        'price' => 350000,
        'category' => 'T-Shirt',
        'heritage' => 'Wayang Kulit',
        'description' => 'Wayang kulit diadaptasi ke estetika komik modern dengan kontras warna tegas.',
        'story' => 'Menjembatani wayang sebagai narasi klasik dengan panel komik—storytelling visual untuk audiens yang tumbuh dengan komik dan animasi.',
        'image' => 'wayang-comic.jpg',
        'featured' => true,
        'stock' => 38,
    ],
    [
        'id' => 'batik-fractal-hoodie',
        'name' => 'Batik Fractal Hoodie',
        'price' => 550000,
        'category' => 'Hoodie',
        'heritage' => 'Batik Kontemporer',
        'description' => 'Pola batik yang direpetisi secara fraktal untuk tekstur yang dinamis namun tetap bermakna.',
        'story' => 'Eksplorasi matematika dan warisan—batik sebagai pola tak hingga yang juga mencerminkan keberlanjutan budaya.',
        'image' => 'batik-fractal.jpg',
        'featured' => true,
        'stock' => 24,
    ],
    [
        'id' => 'reog-anime-streetwear',
        'name' => 'Reog x Anime Streetwear',
        'price' => 450000,
        'category' => 'T-Shirt',
        'heritage' => 'Reog Ponorogo',
        'description' => 'Reog dan anime streetwear bertemu dalam satu siluet yang berani.',
        'story' => 'Menghormati energi pertunjukan Reog dengan bahasa visual yang familier bagi penggemar budaya pop Jepang.',
        'image' => 'reog-anime.jpg',
        'featured' => false,
        'stock' => 30,
    ],
    [
        'id' => 'borobudur-minimalist-tee',
        'name' => 'Borobudur Minimalist Tee',
        'price' => 325000,
        'category' => 'T-Shirt',
        'heritage' => 'Candi Borobudur',
        'description' => 'Siluet stupa dan langgam relief dalam komposisi minimal yang elegan.',
        'story' => 'Mengajak wearer merasakan ketenangan spiritual Borobudur tanpa ornamen berlebihan—less is more.',
        'image' => 'borobudur-minimal.jpg',
        'featured' => false,
        'stock' => 55,
    ],
    [
        'id' => 'ondel-graffiti-jacket',
        'name' => 'Ondel-Ondel Graffiti Jacket',
        'price' => 750000,
        'category' => 'Jacket',
        'heritage' => 'Ondel-Ondel Betawi',
        'description' => 'Ondel-Ondel dalam ekspresi graffiti urban Jakarta.',
        'story' => 'Simbol kota yang dilukis ulang sebagai artefak jalanan—identitas Betawi dalam ritme kota.',
        'image' => 'ondel-graffiti.jpg',
        'featured' => false,
        'stock' => 15,
    ],
    [
        'id' => 'long-sleeve-parang',
        'name' => 'Parang Fusion Long Sleeve',
        'price' => 420000,
        'category' => 'Long Sleeve',
        'heritage' => 'Batik Parang',
        'description' => 'Motif parang halus dengan pewarnaan moody untuk layering sehari-hari.',
        'story' => 'Parang sebagai gelombang kontinuitas—dimaknai sebagai perjalanan, bukan sekadar pola.',
        'image' => 'parang-long.jpg',
        'featured' => false,
        'stock' => 28,
    ],
];
